import { vi } from 'vitest';

export const captureException = vi.fn();
